insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Pepsi", "drink", 1500, "Pepsi", 150, "This is Pepsi")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Fanta", "drink", 1300, "Coca-Cola", 130, "This is Fanta")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Coca-Cola", "drink", 1700, "Coca-Cola", 50, "This is Coca-Cola")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Chilsung-Cider", "drink", 1900, "Lotte", 100, "This is Chilsung-Cider")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Nunethine", "snack", 3200, "Samlip", 170, "This is Nunethine")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Binch", "snack", 3000, "Lotte", 200, "This is Binch")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("ChocoPie", "snack", 5500, "Orion", 65, "This is ChocoPie")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Couque d'Asse", "snack", 3000, "Crown", 190, "This is Couque d'Asse")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("OYes", "snack", 5000, "HaiTai", 220, "This is OYes")
insert into product_table(name, category, price, manufacturer, unit_in_stock, description) values ("Homerunball", "snack", 2000, "HaiTai", 210, "This is Homerunball")